Repository jakartaresearch/earth-vision, pull requests merged in 2021-05, with the labels that each got.

#39 Initialize CONTRIBUTING.md and test script for initial testing
  CONTRIBUTING.md
  README.md
  test.py
Labels: documentation

#46 update requirements and gitignore
  .gitignore
  requirements.txt
Labels: priority: medium, work: obvious

#45 Aerial cactus
  earthvision/datasets/__init__.py
  earthvision/datasets/aerialcactus.py
  earthvision/datasets/utils.py
  test.ipynb
Labels: priority: medium, type: feature, work: obvious
